<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ForumDiscussion extends \App\Entity\ForumDiscussion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'authorName' => [parent::class, 'authorName', null, 16],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null, 16],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isLocked' => [parent::class, 'isLocked', null, 16],
        "\0".parent::class."\0".'isPinned' => [parent::class, 'isPinned', null, 16],
        "\0".parent::class."\0".'messages' => [parent::class, 'messages', null, 16],
        "\0".parent::class."\0".'solved' => [parent::class, 'solved', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'views' => [parent::class, 'views', null, 16],
        "\0".parent::class."\0".'viewsCollection' => [parent::class, 'viewsCollection', null, 16],
        'authorName' => [parent::class, 'authorName', null, 16],
        'category' => [parent::class, 'category', null, 16],
        'content' => [parent::class, 'content', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isLocked' => [parent::class, 'isLocked', null, 16],
        'isPinned' => [parent::class, 'isPinned', null, 16],
        'messages' => [parent::class, 'messages', null, 16],
        'solved' => [parent::class, 'solved', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'views' => [parent::class, 'views', null, 16],
        'viewsCollection' => [parent::class, 'viewsCollection', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
