<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OPtI6lKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OPtI6lK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OPtI6lK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reportRepository' => ['privates', 'App\\Repository\\ForumReportRepository', 'getForumReportRepositoryService', true],
        ], [
            'reportRepository' => 'App\\Repository\\ForumReportRepository',
        ]);
    }
}
