<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__BIAD0KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..bIAD0K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..bIAD0K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\ForumCategoryRepository', 'getForumCategoryRepositoryService', true],
            'discussionRepository' => ['privates', 'App\\Repository\\ForumDiscussionRepository', 'getForumDiscussionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categoryRepository' => 'App\\Repository\\ForumCategoryRepository',
            'discussionRepository' => 'App\\Repository\\ForumDiscussionRepository',
            'entityManager' => '?',
        ]);
    }
}
