<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GGskixqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gGskixq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gGskixq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discussionRepository' => ['privates', 'App\\Repository\\ForumDiscussionRepository', 'getForumDiscussionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'messageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
            'reportRepository' => ['privates', 'App\\Repository\\ForumReportRepository', 'getForumReportRepositoryService', true],
        ], [
            'discussionRepository' => 'App\\Repository\\ForumDiscussionRepository',
            'entityManager' => '?',
            'messageRepository' => 'App\\Repository\\ForumMessageRepository',
            'reportRepository' => 'App\\Repository\\ForumReportRepository',
        ]);
    }
}
