<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HtiLOFGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HtiLOFG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HtiLOFG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discussion' => ['privates', '.errored..service_locator.HtiLOFG.App\\Entity\\ForumDiscussion', NULL, 'Cannot autowire service ".service_locator.HtiLOFG": it needs an instance of "App\\Entity\\ForumDiscussion" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'discussion' => 'App\\Entity\\ForumDiscussion',
            'entityManager' => '?',
        ]);
    }
}
