<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__VLdGgyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..VLdGgy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..VLdGgy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'messageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
            'parentMessage' => ['privates', '.errored..service_locator..VLdGgy.App\\Entity\\ForumMessage', NULL, 'Cannot autowire service ".service_locator..VLdGgy": it needs an instance of "App\\Entity\\ForumMessage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'messageRepository' => 'App\\Repository\\ForumMessageRepository',
            'notificationService' => 'App\\Service\\NotificationService',
            'parentMessage' => 'App\\Entity\\ForumMessage',
        ]);
    }
}
