<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DM85oHFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DM85oHF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DM85oHF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.DM85oHF.App\\Entity\\ForumCategory', NULL, 'Cannot autowire service ".service_locator.DM85oHF": it needs an instance of "App\\Entity\\ForumCategory" but this type has been excluded in "config/services.yaml".'],
            'discussionRepository' => ['privates', 'App\\Repository\\ForumDiscussionRepository', 'getForumDiscussionRepositoryService', true],
        ], [
            'category' => 'App\\Entity\\ForumCategory',
            'discussionRepository' => 'App\\Repository\\ForumDiscussionRepository',
        ]);
    }
}
