<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VcCsXmJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vcCsXmJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vcCsXmJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discussion' => ['privates', '.errored..service_locator.vcCsXmJ.App\\Entity\\ForumDiscussion', NULL, 'Cannot autowire service ".service_locator.vcCsXmJ": it needs an instance of "App\\Entity\\ForumDiscussion" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'messageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
            'viewRepository' => ['privates', 'App\\Repository\\ForumViewRepository', 'getForumViewRepositoryService', true],
        ], [
            'discussion' => 'App\\Entity\\ForumDiscussion',
            'entityManager' => '?',
            'messageRepository' => 'App\\Repository\\ForumMessageRepository',
            'notificationService' => 'App\\Service\\NotificationService',
            'viewRepository' => 'App\\Repository\\ForumViewRepository',
        ]);
    }
}
