<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W7mY39kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W7mY39k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W7mY39k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepository' => ['privates', 'App\\Repository\\ForumCategoryRepository', 'getForumCategoryRepositoryService', true],
            'discussionRepository' => ['privates', 'App\\Repository\\ForumDiscussionRepository', 'getForumDiscussionRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\ForumCategoryRepository',
            'discussionRepository' => 'App\\Repository\\ForumDiscussionRepository',
        ]);
    }
}
