<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BBPCyMYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BBPCyMY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BBPCyMY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discussionRepository' => ['privates', 'App\\Repository\\ForumDiscussionRepository', 'getForumDiscussionRepositoryService', true],
            'messageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
        ], [
            'discussionRepository' => 'App\\Repository\\ForumDiscussionRepository',
            'messageRepository' => 'App\\Repository\\ForumMessageRepository',
        ]);
    }
}
