<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KhU4g4WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KhU4g4W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KhU4g4W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'messageRepository' => ['privates', 'App\\Repository\\ForumMessageRepository', 'getForumMessageRepositoryService', true],
        ], [
            'entityManager' => '?',
            'messageRepository' => 'App\\Repository\\ForumMessageRepository',
        ]);
    }
}
