<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailVerificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailVerificationService' shared autowired service.
     *
     * @return \App\Service\EmailVerificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EmailVerificationService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }

        $instance = new \App\Service\EmailVerificationService($a, ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['router'] ?? self::getRouterService($container)), $container->getEnv('MAILER_FROM_EMAIL'));

        if (isset($container->privates['App\\Service\\EmailVerificationService'])) {
            return $container->privates['App\\Service\\EmailVerificationService'];
        }

        return $container->privates['App\\Service\\EmailVerificationService'] = $instance;
    }
}
