<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForumMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..VLdGgy.App\Entity\ForumMessage' shared service.
     *
     * @return \App\Entity\ForumMessage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..VLdGgy": it needs an instance of "App\\Entity\\ForumMessage" but this type has been excluded in "config/services.yaml".');
    }
}
