<?php

namespace ContainerPLk0h30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForumDiscussion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vcCsXmJ.App\Entity\ForumDiscussion' shared service.
     *
     * @return \App\Entity\ForumDiscussion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.vcCsXmJ": it needs an instance of "App\\Entity\\ForumDiscussion" but this type has been excluded in "config/services.yaml".');
    }
}
