<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPLk0h30\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPLk0h30/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPLk0h30.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPLk0h30\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPLk0h30\App_KernelDevDebugContainer([
    'container.build_hash' => 'PLk0h30',
    'container.build_id' => 'a9b7fe7e',
    'container.build_time' => 1778541786,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPLk0h30');
